### ISSUE TITLE
"Export notebook as..." was missing from some user's menus and not from others

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/metalc#59]
A student asked me in class today if you can export the notebok as a python script. I couldn't find the button to do so in the jupyterlab menu. But then the student said he saw "Export Notebook As..". Some other students did not see it in their menu either. When I got back to my office I had to restart my session and I now see the menu item. Not sure how to reproduce but I'll be on the lookout for it missing again.

**Comment by celine168** [comment]
Something I noticed: when I spawn the server for the first time, the button doesn't show. After refreshing the page, it shows up. I don't know if this is a regular pattern though.

**Comment by moorepants** [comment]
Please add a note to the FAQ that refreshing the browser is sometimes needed to make sure all jupyterlab menu items show. Then also open and issue on JupyterLab that explains this.

**Comment by moorepants** [comment]
Haven't seen the crop up, so maybe it is fixed. We can reopen if needed.

**Comment by bettytan123** [comment]
may i ask i am still seeing this issue in my end, i do not have the download as button in my Jupiter notebook?
